// QR pairing flow per spec/10-auth.md § "Surface linking (QR flow)".
//
// Server-as-credential-authority model:
//   - Any already-linked surface opens a pairing window by asking the server
//     for a single-use nonce (authenticated with its own credential). The
//     opener does NOT know the new surface's public key, so the nonce binds
//     to nothing but itself + an expiry.
//   - The new surface generates its device keypair, scans the QR, and submits
//     { nonce, devicePublicKey, clientType } to the server.
//   - The SERVER mints the new surface's credential with the account PRIVATE
//     key, binding `pairing_nonce` + `surface_pubkey`, then consumes the nonce.
//
// This package is wire-transport agnostic: the server owns the WS relay and
// the persistent registry. Here we ship the nonce store + a pure
// `completePairing` helper the server calls at /api/auth/pair/complete.

import { randomBytes as nobleRandomBytes } from '@noble/hashes/utils';
import { mintSurfaceCredential, type SurfaceKind } from './jwt.js';
import { bytesToBase64Url } from './base64url.js';
import { publicKeyBytes } from './identity.js';
import {
  PairingNonceExpiredError,
  PairingNonceUnknownError,
  CredentialVerificationError,
} from './errors.js';

export const PAIRING_NONCE_TTL_MS = 5 * 60 * 1000;
export const PAIRING_NONCE_BYTES = 32;

export interface CreatedPairingNonce {
  nonce: string;
  expiresAt: number;
}

export interface CreatePairingNonceOptions {
  randomBytes?: (n: number) => Uint8Array;
  /** Unix milliseconds — pairing/nonce times are in ms (vs JWT seconds). */
  nowMs?: number;
}

export function createPairingNonce(opts: CreatePairingNonceOptions = {}): CreatedPairingNonce {
  const rand = opts.randomBytes ?? nobleRandomBytes;
  const bytes = rand(PAIRING_NONCE_BYTES);
  if (bytes.length !== PAIRING_NONCE_BYTES) {
    throw new Error(
      `createPairingNonce: randomBytes returned ${bytes.length} bytes, expected ${PAIRING_NONCE_BYTES}`,
    );
  }
  const nowMs = opts.nowMs ?? Date.now();
  return {
    nonce: bytesToBase64Url(bytes),
    expiresAt: nowMs + PAIRING_NONCE_TTL_MS,
  };
}

/**
 * A pending pairing window. The opener does NOT know the new surface's public
 * key when it opens the window, so the record binds only to the nonce + an
 * expiry. The device key is bound at `completePairing` time.
 */
export interface PairingNonceRecord {
  nonce: string;
  expiresAt: number;
}

export interface CompletePairingOptions {
  /** The single-use nonce shown on the QR. */
  nonce: string;
  /** Base64url Ed25519 public key generated by the new surface. */
  devicePublicKey: string;
  /** What the new surface IS. */
  surface: { kind: SurfaceKind; label: string; surfaceId: string };
  /**
   * Account Ed25519 PRIVATE key. The server is the credential authority and
   * signs the new surface's credential with it. NEVER leaves the server.
   */
  accountPrivateKey: string;
  /** Nonce store — must contain an unexpired record for `nonce`. */
  nonceStore: PairingNonceStore;
  /** JWT exp claim, unix seconds. Optional (mintSurfaceCredential defaults it). */
  expiresAt?: number;
  /** Override now() for testing — defaults to Date.now(). Unix milliseconds. */
  nowMs?: number;
}

/**
 * Server-side pairing completion. Validates the nonce (exists + unexpired),
 * mints the new surface's credential with the account private key (binding
 * `pairing_nonce` + `surface_pubkey`), and single-use consumes the nonce only
 * AFTER a successful mint.
 *
 * Throws `PairingNonceUnknownError` / `PairingNonceExpiredError` for bad nonces
 * and `CredentialVerificationError` for a malformed device public key — all
 * known client-input errors the route maps to 400. NO FALLBACK.
 */
export async function completePairing(
  opts: CompletePairingOptions,
): Promise<{ credential: string; surfaceId: string }> {
  if (!opts.nonceStore) {
    throw new TypeError('completePairing requires opts.nonceStore');
  }
  const nowMs = opts.nowMs ?? Date.now();

  const record = opts.nonceStore.get(opts.nonce);
  if (!record) throw new PairingNonceUnknownError();
  if (record.expiresAt <= nowMs) throw new PairingNonceExpiredError();

  // The device public key is used as a credential binding and (by the server)
  // to address the relay WS — it must be a well-formed Ed25519 public key.
  // Checked BEFORE we reserve the nonce so a malformed key never burns it.
  if (publicKeyBytes(opts.devicePublicKey).length !== 32) {
    throw new CredentialVerificationError('devicePublicKey is not a valid Ed25519 public key');
  }

  // TOCTOU fix (M3): atomically reserve-and-remove the nonce BEFORE the async
  // mint. Two concurrent completes race here, but `take` is a single
  // synchronous get-and-delete, so exactly one wins (returns the record) and
  // the loser sees `undefined` → PairingNonceUnknownError. This closes the
  // double-spend window where both calls could pass the `get`/expiry checks
  // before either consumed the single-use nonce.
  const reserved = opts.nonceStore.take(opts.nonce);
  if (!reserved) throw new PairingNonceUnknownError();

  let credential: string;
  try {
    credential = await mintSurfaceCredential({
      userPrivateKey: opts.accountPrivateKey,
      surfaceId: opts.surface.surfaceId,
      surfaceKind: opts.surface.kind,
      label: opts.surface.label,
      expiresAt: opts.expiresAt,
      now: Math.floor(nowMs / 1000),
      pairingNonce: opts.nonce,
      surfacePubkey: opts.devicePublicKey,
    });
  } catch (e) {
    // A failed mint must NOT burn the legitimate user's nonce (DoS resistance):
    // put the reserved record back so the user can retry.
    opts.nonceStore.put(reserved);
    throw e;
  }

  return { credential, surfaceId: opts.surface.surfaceId };
}

/**
 * In-memory nonce store. The server wraps this with persistence if needed;
 * for now nonces are short-lived (5 min) so memory is fine.
 */
export interface PairingNonceStore {
  put(record: PairingNonceRecord): void;
  get(nonce: string): PairingNonceRecord | undefined;
  /**
   * Atomically return-and-remove the record for `nonce` in ONE synchronous
   * step. Returns the record if it existed (and removes it), or `undefined` if
   * it was absent. This single-step semantics is what makes single-use
   * enforcement race-free under concurrent completes (M3 TOCTOU fix): two
   * callers both reach `take`, but only one gets the record back.
   */
  take(nonce: string): PairingNonceRecord | undefined;
}

export interface InMemoryPairingNonceStoreOptions {
  /** Maximum entries; once exceeded, oldest (FIFO insertion order) are dropped. Default 10000. */
  maxEntries?: number;
  /** Override clock for tests — default Date.now. */
  now?: () => number;
}

export const DEFAULT_NONCE_STORE_MAX_ENTRIES = 10_000;

export class InMemoryPairingNonceStore implements PairingNonceStore {
  // Map preserves insertion order — first key is the oldest entry.
  private records = new Map<string, PairingNonceRecord>();
  private readonly maxEntries: number;
  private readonly nowFn: () => number;

  constructor(opts: InMemoryPairingNonceStoreOptions = {}) {
    this.maxEntries = opts.maxEntries ?? DEFAULT_NONCE_STORE_MAX_ENTRIES;
    if (this.maxEntries <= 0) {
      throw new Error('InMemoryPairingNonceStore: maxEntries must be > 0');
    }
    this.nowFn = opts.now ?? ((): number => Date.now());
  }

  put(record: PairingNonceRecord): void {
    // Auto-prune-expired BEFORE insertion so dead nonces don't push live ones out.
    this.prune(this.nowFn());
    // If the same nonce is being re-inserted, remove first so it's re-ordered to the tail.
    if (this.records.has(record.nonce)) this.records.delete(record.nonce);
    this.records.set(record.nonce, record);
    // Cap: drop oldest until under the limit.
    while (this.records.size > this.maxEntries) {
      const oldest = this.records.keys().next().value;
      // Unreachable: the loop condition (size > maxEntries, maxEntries > 0
      // enforced by the constructor) only holds when size >= 2, so the
      // Map's key iterator always has a first value here. Defensive guard
      // against a future refactor changing that invariant.
      /* v8 ignore next */
      if (oldest === undefined) break;
      this.records.delete(oldest);
    }
  }
  get(nonce: string): PairingNonceRecord | undefined {
    return this.records.get(nonce);
  }
  take(nonce: string): PairingNonceRecord | undefined {
    const record = this.records.get(nonce);
    if (record === undefined) return undefined;
    this.records.delete(nonce);
    return record;
  }
  /** Remove all expired entries. `nowMs` is unix milliseconds. */
  prune(nowMs: number = Date.now()): void {
    for (const [k, v] of this.records.entries()) {
      if (v.expiresAt <= nowMs) this.records.delete(k);
    }
  }
  /** Test introspection. */
  size(): number {
    return this.records.size;
  }
}
